on:
  push:
    branches:
    - master


steps:
  - id: auth
    uses: google-github-actions/auth@v0.4.0
    with:
      workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
      service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
  - id: upload-files
    uses: google-github-actions/upload-cloud-storage@v0.4.0
    with:
      path: /path/to/folder
      destination: bucket-name